CREATE DATABASE IF NOT EXISTS COLLEGE;
USE COLLEGE;


CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT,
GREADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO STUDENTS
VALUES
(101,"anil",78,"C","Pune"),
(102,"bhumika",93,"A","Mumbai"),
(103,"Chetan",85,"A","Mumbai"),
(104,"dhruv",85,"A","Delhi"),
(105,"emanul",12,"F","Delhi"),
(106,"farah",82,"B","Delhi");

-- ADD COLUMN USING ALTER METHOD:  
ALTER TABLE STUDENTS
ADD COLUMN AGE INT NOT NULL DEFAULT 19;

-- DROP COLUMN USING ALTER METHOD:
ALTER TABLE STUDENT
DROP COLUMN AGE ; 

-- RENAME COLUMN USING ALTER METHOD
ALTER TABLE STUDENT
RENAME TO STUDENTS; 


--  MODIFY COLUMN
ALTER TABLE STUDENTS
MODIFY COLUMN AGE VARCHAR(2);


INSERT INTO STUDENTS
(ID,NAME,MARKS,AGE)
VALUES
(108,"G1",99,19);

--  [CHANGE COLUMN (RENAME)] CHANGE COLUMN NAME AND TYPE

ALTER TABLE STUDENTS
CHANGE COLUMN AGE STUD_AGE INT NOT NULL;


-- DROP COLUMN [ DROP COLUMN]
ALTER TABLE STUDENTS
DROP COLUMN STUD_AGE; 


-- TRUNCATE [ TO DELETE TABLE DATA , TABLE WILL EXIST]
TRUNCATE TABLE STUDENTS; 

DROP DATABASE COLLEGE;   
SELECT * FROM STUDENTS;